apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: tn5u5rph3-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:60777ec4821d3c5fe6d53ee547e1252e2bbaf323@sha256:9c26bce7ac1edf41a26f6f09d59b0f2f0003a0dccb89f7e3791e15835f21983a
          name: container-image
